### ISSUE TITLE
Pequeño bug al activar editor Wysibb

### ISSUE THREAD

**Issue by Arluis** [risus2/risus2#3]
Hola, antes que nada felicitarlos por continuar conel proyecto, bueno algrano:

Testeando en el Localhost, me encontré con un pequeño problema, al ser responsive el theme por default, al activar el editor **Wysibb**  éste se sale de la barra de comentarios al intentar reducir el tamaño de la ventana.
![captura](https://user-images.githubusercontent.com/36287523/36010351-f4174954-0d1e-11e8-8ea3-8449f42b9975.PNG)

**Comment by joelmiguelvalente** [comment]
Ahora en poco te enviaré la solución! lamento la tardanza

**Comment by MrDioamDev** [comment]
Resulta que debido a que el Wysibb no lo han actualizado, pues el CSS es viejo y no es responsive...
Ya Miguel al parecer te enviará la solución.

**Comment by joelmiguelvalente** [comment]
Hola, como ha dicho mi colega, al ser **CSS viejo** hay que hacer una **reestructuración para hacerla responsive**, ya cuando salió el wysibb no se usaba tanto la forma responsive....Así que tardaré un poco más de lo que había pensado.

Ej: porque si se modifica el área de comentarios, se desarma(se ve mal) al crear post...
